// Generated by gencpp from file hps_camera/cameraResponse.msg
// DO NOT EDIT!


#ifndef HPS_CAMERA_MESSAGE_CAMERARESPONSE_H
#define HPS_CAMERA_MESSAGE_CAMERARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hps_camera
{
template <class ContainerAllocator>
struct cameraResponse_
{
  typedef cameraResponse_<ContainerAllocator> Type;

  cameraResponse_()
    : control_cmd()  {
    }
  cameraResponse_(const ContainerAllocator& _alloc)
    : control_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _control_cmd_type;
  _control_cmd_type control_cmd;





  typedef boost::shared_ptr< ::hps_camera::cameraResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hps_camera::cameraResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cameraResponse_

typedef ::hps_camera::cameraResponse_<std::allocator<void> > cameraResponse;

typedef boost::shared_ptr< ::hps_camera::cameraResponse > cameraResponsePtr;
typedef boost::shared_ptr< ::hps_camera::cameraResponse const> cameraResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hps_camera::cameraResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hps_camera::cameraResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hps_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hps_camera': ['/mnt/hgfs/UbuntuShare/HPS3D_SDK_ROS_DEMO/src/hps_camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hps_camera::cameraResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hps_camera::cameraResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hps_camera::cameraResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hps_camera::cameraResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hps_camera::cameraResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hps_camera::cameraResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hps_camera::cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39d7f0ad14e9dfe7d61de4ee6470c2d8";
  }

  static const char* value(const ::hps_camera::cameraResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39d7f0ad14e9dfe7ULL;
  static const uint64_t static_value2 = 0xd61de4ee6470c2d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hps_camera::cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hps_camera/cameraResponse";
  }

  static const char* value(const ::hps_camera::cameraResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hps_camera::cameraResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string control_cmd\n\
\n\
";
  }

  static const char* value(const ::hps_camera::cameraResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hps_camera::cameraResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cameraResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hps_camera::cameraResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hps_camera::cameraResponse_<ContainerAllocator>& v)
  {
    s << indent << "control_cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.control_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HPS_CAMERA_MESSAGE_CAMERARESPONSE_H
