// Generated by gencpp from file hps_camera/PointCloudData.msg
// DO NOT EDIT!


#ifndef HPS_CAMERA_MESSAGE_POINTCLOUDDATA_H
#define HPS_CAMERA_MESSAGE_POINTCLOUDDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hps_camera
{
template <class ContainerAllocator>
struct PointCloudData_
{
  typedef PointCloudData_<ContainerAllocator> Type;

  PointCloudData_()
    : x()
    , y()
    , z()
    , width(0)
    , height(0)
    , points(0)
    , distance_average(0)  {
    }
  PointCloudData_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , z(_alloc)
    , width(0)
    , height(0)
    , points(0)
    , distance_average(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _z_type;
  _z_type z;

   typedef uint16_t _width_type;
  _width_type width;

   typedef uint16_t _height_type;
  _height_type height;

   typedef uint16_t _points_type;
  _points_type points;

   typedef uint16_t _distance_average_type;
  _distance_average_type distance_average;





  typedef boost::shared_ptr< ::hps_camera::PointCloudData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hps_camera::PointCloudData_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloudData_

typedef ::hps_camera::PointCloudData_<std::allocator<void> > PointCloudData;

typedef boost::shared_ptr< ::hps_camera::PointCloudData > PointCloudDataPtr;
typedef boost::shared_ptr< ::hps_camera::PointCloudData const> PointCloudDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hps_camera::PointCloudData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hps_camera::PointCloudData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hps_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hps_camera': ['/mnt/hgfs/UbuntuShare/HPS3D_SDK_ROS_DEMO/src/hps_camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hps_camera::PointCloudData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hps_camera::PointCloudData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hps_camera::PointCloudData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hps_camera::PointCloudData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hps_camera::PointCloudData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hps_camera::PointCloudData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hps_camera::PointCloudData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9512facb125a4b5d4f71e2234ee7eaf8";
  }

  static const char* value(const ::hps_camera::PointCloudData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9512facb125a4b5dULL;
  static const uint64_t static_value2 = 0x4f71e2234ee7eaf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hps_camera::PointCloudData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hps_camera/PointCloudData";
  }

  static const char* value(const ::hps_camera::PointCloudData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hps_camera::PointCloudData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n\
float32[] y\n\
float32[] z\n\
uint16 width\n\
uint16 height\n\
uint16 points\n\
\n\
uint16 distance_average\n\
\n\
";
  }

  static const char* value(const ::hps_camera::PointCloudData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hps_camera::PointCloudData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.points);
      stream.next(m.distance_average);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloudData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hps_camera::PointCloudData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hps_camera::PointCloudData_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.z[i]);
    }
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.height);
    s << indent << "points: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.points);
    s << indent << "distance_average: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.distance_average);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HPS_CAMERA_MESSAGE_POINTCLOUDDATA_H
