# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hps_camera/measureData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hps_camera.msg

class measureData(genpy.Message):
  _md5sum = "d25e7f28a0c985f85d20386b940737b5"
  _type = "hps_camera/measureData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """hps_camera/PointCloudData point_cloud_data

================================================================================
MSG: hps_camera/PointCloudData
float32[] x
float32[] y
float32[] z
uint16 width
uint16 height
uint16 points

uint16 distance_average

"""
  __slots__ = ['point_cloud_data']
  _slot_types = ['hps_camera/PointCloudData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       point_cloud_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(measureData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.point_cloud_data is None:
        self.point_cloud_data = hps_camera.msg.PointCloudData()
    else:
      self.point_cloud_data = hps_camera.msg.PointCloudData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.point_cloud_data.x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.point_cloud_data.x))
      length = len(self.point_cloud_data.y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.point_cloud_data.y))
      length = len(self.point_cloud_data.z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.point_cloud_data.z))
      _x = self
      buff.write(_get_struct_4H().pack(_x.point_cloud_data.width, _x.point_cloud_data.height, _x.point_cloud_data.points, _x.point_cloud_data.distance_average))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.point_cloud_data is None:
        self.point_cloud_data = hps_camera.msg.PointCloudData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.point_cloud_data.x = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.point_cloud_data.y = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.point_cloud_data.z = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 8
      (_x.point_cloud_data.width, _x.point_cloud_data.height, _x.point_cloud_data.points, _x.point_cloud_data.distance_average,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.point_cloud_data.x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.point_cloud_data.x.tostring())
      length = len(self.point_cloud_data.y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.point_cloud_data.y.tostring())
      length = len(self.point_cloud_data.z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.point_cloud_data.z.tostring())
      _x = self
      buff.write(_get_struct_4H().pack(_x.point_cloud_data.width, _x.point_cloud_data.height, _x.point_cloud_data.points, _x.point_cloud_data.distance_average))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.point_cloud_data is None:
        self.point_cloud_data = hps_camera.msg.PointCloudData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.point_cloud_data.x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.point_cloud_data.y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.point_cloud_data.z = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 8
      (_x.point_cloud_data.width, _x.point_cloud_data.height, _x.point_cloud_data.points, _x.point_cloud_data.distance_average,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
